### ISSUE TITLE
Research state of OpenSidewalks

### ISSUE THREAD

**Issue by bilsch** [opencolumbus/opencolumbus.github.io#4]
Note the scope of this card is to determine if the projects by https://www.opensidewalks.com/ are viable for our intent / purposes. 

Some questions:

1. Can we just use whatever OpenSidewalks has already online and just turn this into a crowd sourcing need?
2. Would we want / need to run our own stack of their software?
3. With the software components are there any changes necessary? Patching for currency ( eg upgrade libs and such to help out ), documentation to help etc?
4. Does the upstream project(s) need help getting software features completed / implemented?

The goal I have for the initial phase of this project is to ensure we are not duplicating other community efforts. If there are ways for us to collaborate with this project we should absolutely do this over going it our own way.

minor refinement - review the video from the may meetup and figure out where we go next

**Comment by bilsch** [comment]
Reached out to https://github.com/ProjectSidewalk/SidewalkWebpage maintainer to see what all is involved in setting things up for our city / use.

Assuming its as simple to work with as https://sidewalk-sea.cs.washington.edu/validate the scope of our project could change dramatically which is actually really *good*

**Comment by bilsch** [comment]
Not sure if this is the same but this should be the project from Anat and Nick. https://news.cs.washington.edu/2017/02/02/uws-accessmap-makes-navigating-seattle-safer-and-more-accessible-for-all/

I'm wondering if these are two different projects / approaches

**Comment by bilsch** [comment]
**Note** This was originally confused to be related to the OpenSidewalks project. We moved this thread over to #5 - preserving this comment for historical purposes ;)

---

Email corresp for tracking

```
Hi Bill,

Great to hear from you. I took a look at what y'all are doing in your meetup group and I love it!

> It looks like for a new city we would want to set up our own
runtime of https://github.com/ProjectSidewalk/SidewalkWebpage and work
with someone ( you? ) to get this stuff up into open street map /
whatever

We've actually never had someone else set up their own runtime of the site, although it should be possible! We would also be interested in hosting this and doing all the backend work. The main reason we don't deploy into new cities is because we need more buy in from the community; we need people willing to host mapathon parties, promote the tool in their city, advertise to friends in their city. If you can get people to use the tool, I feel pretty confident that we would be willing to host the site. Though let me know if you are interested in that, because I should talk to the rest of my team about it as well :)

> Assuming #1 this is purely visual based on the geographic region.
The use of street view data from google means we don't need to
literally go out and geo tag things - is that correct??

Correct!

Would love to hear your other questions!

Best,
Mikey
```

**Comment by scoplin** [comment]
Interesting discussion ongoing with project sidewalk regarding their own future directions.  May influence whether it is something we want to depend on or use.

https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1728

**Comment by grantpayne** [comment]
Would it be possible to obtain data containing the addresses of registered handicap tags for motor vehicle parking?  We could correlate high geographical density of these to potential areas of interest.

**Comment by andrewgoldfarb** [comment]
This project appears to be fully manually crowdsourced with no future goal for machine learning 

They have created a full schema to map sidewalks as both meta data and separate objects in the OSM data model

There is a forked repo for a app called Street Complete that is a UI for providing the correct schema tag to the OSM data model
